version: '3.8'

services:
  biolab-associates:
    build: .
    container_name: biolab-associates-app
    ports:
      - "5000:5000"
    volumes:
      # Mount data directory for persistent storage of JSON files
      - ./data:/app/data
      # Mount logs directory for development
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/login"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - biolab-network

networks:
  biolab-network:
    driver: bridge

# Optional: Add a volume for persistent data storage
volumes:
  biolab-data:
    driver: local 